### ISSUE TITLE
Forked Impressum

### ISSUE THREAD

**Issue by johsteffens** [BeBaxxter/minecraft-core#1]
Hi BeBaxxter,
this message is about your fork of my repo [Impressum](https://github.com/BeBaxxter/Impressum)

My apology for leaving a note at this place. I currently cannot leave a message directly in [your Impressum](https://github.com/BeBaxxter/Impressum), where it would be best placed and I have no better way to contact you.

Would you be so kind to remove my personal data (name, username, address, email) from [your Impressum](https://github.com/BeBaxxter/Impressum)? As it stands at the moment, it could lead to the false impression that I might be responsible for your content.

I assume you forked https://github.com/johsteffens/Impressum because you wanted a template to adapt it to your identity in order to represent your own work. That is fine with me. But let me clarify that I'm no legal expert and therefore do not know if my "Impressum" is actually suitable for your purpose.

If you have questions, feel free to contact [me](https://github.com/johsteffens) by eMail.
(Gerne auch auf Deutsch :-))

Thanks a lot and best wishes for your great Work!

Johannes

**Comment by BeBaxxter** [comment]
Hello,

this was a mistake. Im new to git and want to use it as a template O_O. I dont now that i created a fork. Its now deleted. SORRRY :D.

LG,
Baxx

16 Mar 2021, 23:42 by ***@***.***:

**Comment by johsteffens** [comment]
No problem at all :-) 
In other circumstances forking would be quite a normal thing.

Thanks very much for reacting so quickly.

Johannes
